// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN5M5mQhKepXCFDkMuHhuemnRq32eYnm8',
    appId: '1:950080662234:web:cd0f8ef7f3c5fa14a2d3e3',
    messagingSenderId: '950080662234',
    projectId: 'life-sync-5a353',
    authDomain: 'life-sync-5a353.firebaseapp.com',
    storageBucket: 'life-sync-5a353.appspot.com',
    measurementId: 'G-DKJEP9XMM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUmk_LSUniZdqB0e3ej6QGF7A68R5Z26M',
    appId: '1:950080662234:android:9e3729528432ce87a2d3e3',
    messagingSenderId: '950080662234',
    projectId: 'life-sync-5a353',
    storageBucket: 'life-sync-5a353.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaxs5-1xe_Obf20xbzIGqrTzKTLGrEiGs',
    appId: '1:950080662234:ios:692407203bdd5bf9a2d3e3',
    messagingSenderId: '950080662234',
    projectId: 'life-sync-5a353',
    storageBucket: 'life-sync-5a353.appspot.com',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaxs5-1xe_Obf20xbzIGqrTzKTLGrEiGs',
    appId: '1:950080662234:ios:692407203bdd5bf9a2d3e3',
    messagingSenderId: '950080662234',
    projectId: 'life-sync-5a353',
    storageBucket: 'life-sync-5a353.appspot.com',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN5M5mQhKepXCFDkMuHhuemnRq32eYnm8',
    appId: '1:950080662234:web:a5e17b231f828faba2d3e3',
    messagingSenderId: '950080662234',
    projectId: 'life-sync-5a353',
    authDomain: 'life-sync-5a353.firebaseapp.com',
    storageBucket: 'life-sync-5a353.appspot.com',
    measurementId: 'G-0BYXZ0VYB6',
  );
}
